# Generated by Django 2.2.5 on 2020-04-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_lib', '0003_auto_20200405_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieitem',
            name='full_data',
            field=models.TextField(default='No data'),
        ),
    ]
