# Generated by Django 2.2.5 on 2020-04-05 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies_lib', '0005_commentitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentitem',
            old_name='comment_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='commentitem',
            old_name='comment_id',
            new_name='movie_id',
        ),
        migrations.AddField(
            model_name='commentitem',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
