# Generated by Django 2.2.5 on 2020-04-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_lib', '0006_auto_20200405_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieitem',
            name='poster',
            field=models.TextField(default='Not available'),
        ),
    ]
